import java.io.IOException;

public class Graafikuseedija {
    public static boolean main(String selectedFile, String fileToSave, String[][] shiftSizes) throws IOException {
        ReadFromXLSX.setFileName(selectedFile);
        WriteToXLSX.setFileLocation(fileToSave);

        String[][] week = Parser.parse(shiftSizes);
        // Check if the week generated by parser is a complete week or has some empty shifts
        if (week.length < 4 || week[2][6].length() < 1){
            WriteToXLSX.writeInput(week);
            return false;
        } else {
            WriteToXLSX.writeInput(week);
            return true;
        }

    }
}
