import javax.swing.*;
import javax.swing.filechooser.FileSystemView;
import java.awt.*;
import java.io.File;
import java.io.IOException;
import java.util.Arrays;

public class Graafikuseedija {
    public static boolean main(String selectedFile, String fileToSave, String[][] shiftSizes) throws IOException {
        ReadFromXLSX.setFileName(selectedFile);
        WriteToXLSX.setFileLocation(fileToSave);

        String[][] week = Parser.parse(shiftSizes);
        // Check if the week generated by parser is a complete week or has some empty shifts
        if (week.length < 4 || week[3][6].length() < 1){
            WriteToXLSX.writeInput(week);
            return false;
        } else {
            WriteToXLSX.writeInput(week);
            return true;
        }
    }


        //readFromXML.setFileName("Graafikuseedija/src/WS02-schedule-wishes-Jan-6th-12th_Sven.xlsx");


        /*
        List<worker> workers = readFromXML.readInput();
        for (worker worker: workers){
            System.out.print(worker.getName()+" ");
            for (String day: worker.getDays()){
                System.out.print(day +" ");
            }
            System.out.println();
        }

         */



}
